version: '3.7'

services:
  db:
    image: postgres:14.1-alpine
    restart: on-failure
    volumes:
      - "db0:/var/lib/postgresql/data/"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
        interval: 10s
        timeout: 5s
        retries: 5

  script:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      db:
        condition: "service_healthy"
    command: sh -c "python3 google-image-scraper.py"
volumes:
  db0:
    driver: local